/**
 * AgentContext - Runtime context for Agent
 *
 * Contains agent identity (agentId, createdAt) merged with user config.
 * Passed to Driver on each receive() call.
 */

/**
 * Base context fields (generated by core)
 */
export interface AgentContextBase {
  /**
   * Unique agent instance ID
   */
  readonly agentId: string;

  /**
   * Creation timestamp (milliseconds)
   */
  readonly createdAt: number;
}

/**
 * Full agent context = base fields + user config
 */
export type AgentContext<TConfig = Record<string, unknown>> = AgentContextBase & Readonly<TConfig>;
